### ISSUE TITLE
Add LWT_TOPIC

### ISSUE THREAD

**Issue by Bolukan** [maretodoric/theengsgateway-docker#6]
Could you add the [LWT_TOPIC](https://github.com/theengs/gateway/blob/156a46ae5bd596209edaf6660f0248bea6013f5f/docs/use/use.md?plain=1#L65) which default is [home/TheengsGateway/LWT](https://github.com/theengs/gateway/blob/156a46ae5bd596209edaf6660f0248bea6013f5f/TheengsGateway/__init__.py#L36) to the supported [environment variables](https://github.com/maretodoric/theengsgateway-docker/blob/9874dfe4a67b0c624ca073c75d0c4145caf37d51/chroot/opt/venv/start.sh#L111) as I prefer a different topic.

If you are (too) busy, but accept a pull request, let me know.

Thx!

**Comment by maretodoric** [comment]
You could add environment variable PARAMS to your docker-compose or via command line to be something like this:
" --lwt_topic <your value>" and it will be appended at runtime.

I'm no longer maintaining this one as i believe theengs forked this repo and now their maintaining their version of docker here:
https://github.com/theengs/gateway-docker

**Comment by Bolukan** [comment]
Ok thx for responding so quick...

The story continues: https://github.com/theengs/gateway/issues/144

**Comment by Bolukan** [comment]
PS: I applied the quick fix and it works:
```yaml
      LWT_TOPIC: ble/theengs/LWT              # does NOT work
      PARAMS: --lwt_topic ble/theengs/LWT
```
